### ISSUE TITLE
RPT spam OBJECT, must be STRING

### ISSUE THREAD

**Issue by Onefox** [secondcoming/ExileTravellingTrader#1]
with the script i am getting a lot of:

 0:43:58 "@ExileServer/log: ERROR: [BIS_fnc_inString] #1: 2b752400# 1057164: canopener_f.p3d is type OBJECT, must be STRING. "" used instead."
 0:43:58 "@ExileServer/log: ERROR: [BIS_fnc_inString] #1: 2b752400# 1057164: canopener_f.p3d is type OBJECT, must be STRING. "" used instead."
 0:43:58 "@ExileServer/log: ERROR: [BIS_fnc_inString] #1: 2b753900# 1057163: canopener_f.p3d is type OBJECT, must be STRING. "" used instead."
 0:43:58 "@ExileServer/log: ERROR: [BIS_fnc_inString] #1: 2b753900# 1057163: canopener_f.p3d is type OBJECT, must be STRING. "" used instead."
 0:43:58 "@ExileServer/log: ERROR: [BIS_fnc_inString] #1: 3feac100# 327232: plot_rust_branka.p3d is type OBJECT, must be STRING. "" used instead."
 0:43:58 "@ExileServer/log: ERROR: [BIS_fnc_inString] #1: 3feac100# 327232: plot_rust_branka.p3d is type OBJECT, must be STRING. "" used instead."

is there a solution for it?

**Comment by secondcoming** [comment]
I think this is unrelated to the addon
